package top.bogey.touch_tool.bean.action;

public enum ActionType {
    // 开始
    MANUAL_START,
    APPLICATION_START,
    APPLICATION_QUIT_START,
    TIME_START,
    NOTIFICATION_START,
    NETWORK_START,
    BATTERY_START,
    SCREEN_START,
    BLUETOOTH_START,
    RECEIVED_SHARE_START,
    OUT_CALL_START,
    INNER_START,

    // 自定义相关
    CUSTOM_START,
    CUSTOM_END,
    EXECUTE_TASK,
    STOP_TASK,
    GET_VARIABLE,
    SET_VARIABLE,

    // 逻辑
    IF_LOGIC,
    WAIT_IF_LOGIC,
    SWITCH_LOGIC,
    CHOICE_LOGIC,
    FOR_LOGIC,
    WHILE_LOGIC,
    SEQUENCE_LOGIC,
    RANDOM_LOGIC,
    PARALLEL_LOGIC,

    // 通用任务
    DELAY,
    LOG,
    STICK,
    CLOSE_STICK,
    CLOSE_ALL_STICK,

    INPUT_CONFIG,
    MARK_AREA,
    SHOW_TEXT,

    // 应用相关
    OPEN_APP,
    OPEN_URI_SCHEME,
    OPEN_SHORTCUT,
    GET_CURRENT_APPLICATION,
    CHECK_IN_APPLICATION,
    STRING_TO_APP,

    // 系统动作
    SHELL,
    SHARE_TO,

    SYSTEM_KEY,

    PLAY_RINGTONE,
    STOP_RINGTONE,
    TEXT_TO_SPEECH,

    VIBRATE,

    SEND_NOTIFICATION,
    SEND_TOAST,

    WRITE_TO_CLIPBOARD,
    READ_FROM_CLIPBOARD,

    SWITCH_SCREEN,
    GET_SCREEN_STATUS,

    SWITCH_CAPTURE,
    CHECK_CAPTURE_READY,

    GET_BATTERY_STATUS,

    GET_NETWORK_STATUS,

    GET_CURRENT_DATE,
    GET_CURRENT_TIME,

    GET_VOLUME,
    SET_VOLUME,

    // 数值
    NUMBER_ADD,
    NUMBER_SUB,
    NUMBER_MUL,
    NUMBER_DIV,
    NUMBER_MOD,
    NUMBER_ABS,
    NUMBER_EQUAL,
    NUMBER_LESS,
    NUMBER_GREATER,
    NUMBER_RANDOM,
    NUMBER_TO_INT,

    CHECK_NUMBER_IN_VALUE_AREA,
    NUMBER_TO_VALUE_AREA,

    MATH_EXPRESSION,

    // 文本获取与检测
    STRING_FROM_OBJECT,
    STRING_TO_NUMBER,
    STRING_APPEND,
    STRING_SUBSTRING,
    STRING_REGEX,
    STRING_SPLIT,
    STRING_EQUAL,
    STRING_REPLACE,
    GET_OCR_TEXT,
    FIND_OCR_TEXT,
    IS_OCR_TEXT_EXIST,
    PARSE_JSON,
    TO_JSON,
    STRING_ENCODE,
    STRING_DECODE,
    STRING_ENCRYPT,

    // 条件
    BOOLEAN_OR,
    BOOLEAN_AND,
    BOOLEAN_NOT,

    // 控件
    FIND_NODE,
    IS_NODE_EXIST,
    GET_NODES_IN_AREA,
    GET_NODE_INFO,
    GET_NODE_CHILDREN,
    GET_NODE_PARENT,
    GET_WINDOWS,
    CHECK_NODE_VALID,

    NODE_TOUCH,
    EDITTEXT_INPUT,
    EDITTEXT_PASTE,

    // 图片
    GET_IMAGE,
    LOAD_IMAGE,
    CROP_IMAGE,
    RESIZE_IMAGE,
    SAVE_IMAGE,
    FIND_IMAGE,
    FIND_IMAGES,
    IS_IMAGE_EXIST,
    TOUCH_IMAGE,
    CREATE_QRCODE,
    PARSE_QRCODE,
    YOLO_DETECT,

    // 颜色
    GET_COLOR,
    FIND_COLORS,
    IS_COLOR_EXIST,
    COLOR_EQUAL,
    TOUCH_COLOR,

    // 区域
    AREA_TO_INT,
    AREA_FROM_INT,
    CHECK_AREA_CONTAIN_POS,
    CHECK_AREA_RELATION,
    GET_AREA_INTERSECTION,
    GET_AREA_CENTER,
    GET_AREA_RANDOM,
    PICK_AREA,

    // 位置
    POINT_FROM_INT,
    POINT_TO_INT,
    POINT_OFFSET,
    POINT_TO_TOUCH,
    POINTS_TO_TOUCH,
    TOUCH,
    TOUCH_POINT,

    // 数组
    LIST_MAKE,
    LIST_SIZE,
    LIST_IS_EMPTY,
    LIST_CONTAIN,
    LIST_ADD,
    LIST_REMOVE,
    LIST_APPEND,
    LIST_CLEAR,
    LIST_GET,
    LIST_CHOICE,
    LIST_SET,
    LIST_INDEX_OF,
    LIST_FOREACH,

    // 字典
    MAP_MAKE,
    MAP_SIZE,
    MAP_IS_EMPTY,
    MAP_CONTAIN_KEY,
    MAP_CONTAIN_VALUE,
    MAP_REMOVE,
    MAP_APPEND,
    MAP_CLEAR,
    MAP_GET,
    MAP_SET,
    MAP_KEYS,
    MAP_VALUES,
    MAP_FOREACH,

    // 变量
    VAR_SET,
    VAR_GET,
}
